[package]
name = "merkle-generator"
author = "DeGatchi"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "0.17.0", features = ["ws", "rustls", "abigen"] }
rs_merkle = "1.2.0"
hex = "0.4.2"